version: '3'
services:

  phpfpm:
    build: docker/phpfpm
    volumes:
      - ./docker/phpfpm/php.ini:/local/etc/php/php.ini:ro
      - .:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    links:
      - mysql

  web:
    image: nginx
    depends_on:
      - phpfpm
    volumes:
      - ./docker/web/local.template:/etc/nginx/conf.d/default.conf:ro
      - ./web:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    ports:
      - ${WEB_PORT}:80
    links:
      - phpfpm

  mysql:
    image: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    # env_file: .env_local_mysql
    environment:
      MYSQL_DATABASE: materialy
      MYSQL_USER: materialy
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
