version: '3'
services:

  phpfpm:
    build: docker/phpfpm
    volumes:
      - ./docker/phpfpm/php.ini:/local/etc/php/php.ini:ro
      - .:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    links:
      - mysql

  web:
    image: nginx
    volumes:
      - ./docker/web/prod.template:/etc/nginx/conf.d/mysite.template
      - ./web:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    expose:
      - 443
    environment:
      VIRTUAL_HOST: http://159.89.27.68/
      VIRTUAL_PROTO: https
      VIRTUAL_PORT: 443
      NGINX_HOST: http://159.89.27.68/
      NGINX_PORT: 443
    command: /bin/bash -c "envsubst '$${NGINX_HOST},$${NGINX_PORT},$${NGINX_CERT_DIR}' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - phpfpm
    links:
      - phpfpm

  mysql:
    image: mysql
    volumes:
      - /srv/data/edukaton/mysql:/var/lib/mysql
    env_file: .env_mysql
    environment:
      MYSQL_DATABASE: edukaton
      MYSQL_USER: edukaton

networks:
  default:
    external:
      name: nginxproxy_default
