<?php

namespace AppBundle\Repository;

/**
 * DictTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DictTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
